version: '3'
services:
  frenzylabs:
    container_name: frenzylabs-devcontainer
    build:
      context: ./
      dockerfile: Dockerfile
    image: "frenzylab/devcontainer:bullseye"

  node:
    container_name: node-devcontainer
    build:
      context: ./environments/node/
      dockerfile: Dockerfile
    image: "frenzylab/node-devcontainer:latest"

