version: '3'
services:
  frenzylabs:
    container_name: frenzylabs
    build:
      context: ./
      dockerfile: Dockerfile
    image: "frenzylab/devcontainer:latest"
    # volumes:
    #   # Mount the root folder that contains .git
    #   - ./:/frenzylabs:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
