version: '3'
services:
  basecontainer:
    container_name: frenzylabs-devcontainer
    build:
      context: ../
      dockerfile: Dockerfile
    image: "frenzylab/devcontainer:latest"
    volumes:
      # Mount the root folder that contains .git
      - ../:/devcontainer:cached
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.aws:/root/.aws
      - ${HOME}/.saml2aws:/root/.saml2aws
      - ${HOME}/.gnupg:/root/.gnupg
      - ${HOME}/.config:/root/.config
    command: /bin/sh -c "while sleep 1000; do :; done"